-- +goose Up
CREATE TABLE IF NOT EXISTS "tasks" (
	"id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"desc" TEXT NOT NULL,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "creator_name" CHAR(40) NOT NULL
);

-- +goose Down
DROP TABLE tasks;
